
export const SELECTION = 'SELECTION';
export const TAB_TYPE = 'TAB_TYPE';
export const CELL_CLICKED = 'CELL_CLICKED';
export const SEND_TO_DETAILS = 'SEND_TO_DETAILS';
export const SUBJECTCELL_CLICKED = 'SUBJECTCELL_CLICKED';
export const BASELINE_CLICKED = 'BASELINE_CLICKED';
export const EVENT_CLICKED = 'EVENT_CLICKED';
export const VTREAT_CLICKED = 'VTREAT_CLICKED';
export const STUDYCELL_CLICKED = 'STUDYCELL_CLICKED';

export const VISITS_CLICKED = 'VISITS_CLICKED';
export const USERS_CLICKED = 'USERS_CLICKED';
export const SITES_CLICKED = 'SITES_CLICKED';
export const VIEWMORE_CLICKED = 'VIEWMORE_CLICKED';
export const STUDYUSERCELL_CLICKED = 'STUDYUSERCELL_CLICKED';
export const STUDYVISITCELL_CLICKED = 'STUDYVISITCELL_CLICKED';

/* AUTHENTICATION CONSTANTS */
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const USER_UNAUTHENTICATED = "USER_UNAUTHENTICATED";


/* AXIOS CONSTANTS */

export const AXIOS_ERROR_WITH_RESPONSE = "AXIOS_ERROR_WITH_RESPONSE";
export const AXIOS_ERROR_OTHER_ERROR = "AXIOS_ERROR_OTHER_ERROR";
export const AXIOS_ERROR_NO_RESPONSE = "AXIOS_ERROR_NO_RESPONSE";
export const AXIOS_ERROR_INTERNAL = "AXIOS_ERROR_INTERNAL";




















